version: "3.9"

services:
  odoo:
    build:
      context: .  # Make sure your Dockerfile is in the same folder
      dockerfile: Dockerfile
    container_name: odoo-dev
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/home/odoo              # Your cloned Odoo source code
      - odoo-data:/var/lib/odoo            # Database filestore
      # - ./extra-addons:/mnt/extra-addons   # Custom addons
    environment:
      - ODOO_RC=/etc/odoo/odoo.conf
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg-data:
  odoo-data:
